"""Generate TypeScript types + Zod validators from the SDK schema registry.

Single source of truth: Pydantic models -> JSON Schema -> TS/Zod. Run in CI (and
by the host's frontend build) so hand-maintained TS can never drift from Python.

    python -m open_notebook_creator_sdk.codegen > creation.generated.ts
    python -m open_notebook_creator_sdk.codegen path/to/creation.generated.ts

Covers the JSON Schema subset our immutable schemas use: object/array/string/
number/integer/boolean, ``$ref``/``$defs``, ``anyOf`` with null (-> nullable),
``required`` (absent -> optional), ``default``.
"""

from __future__ import annotations

import sys
from typing import Any, Dict, Tuple

from .schemas import SCHEMA_REGISTRY


def _pascal(schema_id: str) -> str:
    # "flashcards.v1" -> "FlashcardsV1"
    return "".join(p.capitalize() for p in schema_id.replace(".", "_").split("_"))


def _resolve(node: Dict[str, Any], defs: Dict[str, Any]) -> Dict[str, Any]:
    if "$ref" in node:
        name = node["$ref"].split("/")[-1]
        return defs[name]
    return node


def _is_nullable(node: Dict[str, Any]) -> Tuple[bool, Dict[str, Any]]:
    if "anyOf" in node:
        variants = node["anyOf"]
        non_null = [v for v in variants if v.get("type") != "null"]
        nullable = any(v.get("type") == "null" for v in variants)
        if len(non_null) == 1:
            return nullable, non_null[0]
    return False, node


def _zod(node: Dict[str, Any], defs: Dict[str, Any]) -> str:
    nullable, node = _is_nullable(node)
    node = _resolve(node, defs)
    t = node.get("type")
    if "properties" in node or t == "object":
        if "properties" not in node:
            expr = "z.record(z.string(), z.unknown())"
        else:
            required = set(node.get("required", []))
            fields = []
            for key, prop in node["properties"].items():
                inner = _zod(prop, defs)
                if key not in required:
                    inner += ".optional()"
                fields.append(f"  {key}: {inner},")
            body = "\n".join(fields)
            expr = "z.object({\n" + body + "\n})"
    elif t == "array":
        items = node.get("items", {})
        expr = f"z.array({_zod(items, defs)})"
    elif t == "string":
        expr = "z.string()"
    elif t == "integer" or t == "number":
        expr = "z.number()"
    elif t == "boolean":
        expr = "z.boolean()"
    else:
        expr = "z.unknown()"
    if nullable:
        expr += ".nullable()"
    return expr


def _ts(node: Dict[str, Any], defs: Dict[str, Any]) -> str:
    nullable, node = _is_nullable(node)
    node = _resolve(node, defs)
    t = node.get("type")
    if "properties" in node or t == "object":
        if "properties" not in node:
            base = "Record<string, unknown>"
        else:
            required = set(node.get("required", []))
            parts = []
            for key, prop in node["properties"].items():
                opt = "" if key in required else "?"
                parts.append(f"  {key}{opt}: {_ts(prop, defs)};")
            base = "{\n" + "\n".join(parts) + "\n}"
    elif t == "array":
        base = f"Array<{_ts(node.get('items', {}), defs)}>"
    elif t == "string":
        base = "string"
    elif t in ("integer", "number"):
        base = "number"
    elif t == "boolean":
        base = "boolean"
    else:
        base = "unknown"
    return f"({base} | null)" if nullable else base


def generate() -> str:
    out = [
        "// AUTO-GENERATED by open_notebook_creator_sdk.codegen — DO NOT EDIT.",
        "// Source of truth: open-notebook-creator-sdk SCHEMA_REGISTRY.",
        'import { z } from "zod";',
        "",
    ]
    registry_entries = []
    for schema_id, model in SCHEMA_REGISTRY.items():
        schema = model.model_json_schema()
        defs = schema.get("$defs", {})
        name = _pascal(schema_id)
        out.append(f"// === {schema_id} ===")
        out.append(f"export const {name}Schema = {_zod(schema, defs)};")
        out.append(f"export type {name} = {_ts(schema, defs)};")
        out.append("")
        registry_entries.append(f'  "{schema_id}": {name}Schema,')

    out.append("export const SCHEMA_VALIDATORS: Record<string, z.ZodTypeAny> = {")
    out.extend(registry_entries)
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> None:
    code = generate()
    if len(sys.argv) > 1:
        with open(sys.argv[1], "w") as f:
            f.write(code)
        print(f"wrote {sys.argv[1]}", file=sys.stderr)
    else:
        sys.stdout.write(code)


if __name__ == "__main__":
    main()
